[package]
name = "fdo-data-formats"
version = "0.1.0"
authors = ["Patrick Uiterwijk <patrick@puiterwijk.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10"
log = "0.4"
serde = "1.0"
serde_cbor = "0.11"
serde_int_map = "0.1.2"
serde_int_map_derive = "0.1.2"
serde_repr = "0.1.6"
serde_tuple = "0.5"
thiserror = "1"
aws-nitro-enclaves-cose = { git = "https://github.com/awslabs/aws-nitro-enclaves-cose.git", branch = "main" }
uuid = "0.8"
hex = "0.4"

http = "0.2"
hyper = "0.14"
